In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/home/tec/Projects/machine_learning/dataset/credit_card_frauds.csv')

In [3]:
# Mostra as 5 ultimas linhas do dataset
display(df.tail())

# Retorna o tamanho do dataset no formato (linhas, colunas)
print(f"O dataset possui {df.shape[0]} linhas e {df.shape[1]} colunas.")

# Informações sobre o tipo de dado de cada coluna e a contagem de valores não nulos
df.info()

,trans_date_trans_time,merchant,category,amt,city,state,lat,long,city_pop,job,dob,trans_num,merch_lat,merch_long,is_fraud
339602,2020-12-31 23:57:56,Schmidt-Larkin,home,12.68,Wales,AK,64.7556,-165.6723,145,"Administrator, education",1939-11-09,a8310343c189e4a5b6316050d2d6b014,65.623593,-165.186033,0
339603,2020-12-31 23:58:04,"Pouros, Walker and Spence",kids_pets,13.02,Greenview,CA,41.5403,-122.9366,308,Call centre manager,1958-09-20,bd7071fd5c9510a5594ee196368ac80e,41.973127,-123.553032,0
339604,2020-12-31 23:59:07,Reilly and Sons,health_fitness,43.77,Luray,MO,40.4931,-91.8912,519,Town planner,1966-02-13,9b1f753c79894c9f4b71f04581835ada,39.946837,-91.333331,0
339605,2020-12-31 23:59:15,Rau-Robel,kids_pets,86.88,Burbank,WA,46.1966,-118.9017,3684,Musician,1981-11-29,6c5b7c8add471975aa0fec023b2e8408,46.658340,-119.715054,0
339606,2020-12-31 23:59:24,Breitenberg LLC,travel,7.99,Mesa,ID,44.6255,-116.4493,129,Cartographer,1965-12-15,14392d723bb7737606b2700ac791b7aa,44.470525,-117.080888,0

O dataset possui 339607 linhas e 15 colunas.
<class 'pandas.DataFrame'>
RangeIndex: 339607 entries, 0 to 339606
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   trans_date_trans_time  339607 non-null  str
 1   merchant               339607 non-null  str
 2   category               339607 non-null  str
 3   amt                    339607 non-null  float64
 4   city                   339607 non-null  str
 5   state                  339607 non-null  str
 6   lat                    339607 non-null  float64
 7   long                   339607 non-null  float64
 8   city_pop               339607 non-null  int64
 9   job                    339607 non-null  str
 10  dob                    339607 non-null  str
 11  trans_num              339607 non-null  str
 12  merch_lat              339607 non-null  float64
 13  merch_long             339607 non-null  float64
 14  is_fraud               339607 non-null  int64
dtypes: float64(5), int64(2), str(8)
memory usage: 38.9 MB

In [10]:
# Gera um resumo estatístico (média, desvio padrão, valores mínimos, máximos e quartis)
# Isso ajuda a identificar outliers
display(df.describe())

,amt,lat,long,city_pop,merch_lat,merch_long,is_fraud
count,339607.000000,339607.000000,339607.000000,3.396070e+05,339607.000000,339607.000000,339607.000000
mean,70.577984,39.718991,-110.622605,1.071409e+05,39.718853,-110.622383,0.005247
std,161.675242,5.094961,12.651370,2.930299e+05,5.130894,12.663998,0.072248
min,1.000000,20.027100,-165.672300,4.600000e+01,19.027422,-166.671575,0.000000
25%,9.600000,36.715400,-120.093600,4.710000e+02,36.817194,-119.823755,0.000000
50%,46.460000,39.617100,-111.098500,1.645000e+03,39.586209,-111.036443,0.000000
75%,83.350000,41.710000,-100.621500,3.543900e+04,42.193072,-100.353096,0.000000
max,28948.900000,66.693300,-89.628700,2.383912e+06,67.510267,-88.629203,1.000000

In [4]:
# Quantidade absoluta de transações normais vs fraudes
print(df['is_fraud'].value_counts())

# Proporção em porcentagem
print(df['is_fraud'].value_counts(normalize=True) * 100)

# Visualização gráfica do desbalanceamento
# sns.countplot(x='is_fraud', data=df)
# plt.title('Distribuição das Classes (0: Legítimo, 1: Fraude)')
# plt.show()

is_fraud
0    337825
1      1782
Name: count, dtype: int64
is_fraud
0    99.475276
1     0.524724
Name: proportion, dtype: float64

Análise Exploratória de Dados (EDA)

In [5]:
# Mostra a quantidade de dados nulos por coluna
print(df.isnull().sum())

trans_date_trans_time    0
merchant                 0
category                 0
amt                      0
city                     0
state                    0
lat                      0
long                     0
city_pop                 0
job                      0
dob                      0
trans_num                0
merch_lat                0
merch_long               0
is_fraud                 0
dtype: int64

In [7]:
df.dtypes

trans_date_trans_time        str
merchant                     str
category                     str
amt                      float64
city                         str
state                        str
lat                      float64
long                     float64
city_pop                   int64
job                          str
dob                          str
trans_num                    str
merch_lat                float64
merch_long               float64
is_fraud                   int64
dtype: object